---
title: "Setup for Divvy data analysis"
author: "Peter Carbonetto"
date: 2017-06-29
output: html_document
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

Instructions:

+ How to download the Divvy data. You should have these files in the
data directory:

  ```bash
  README.txt
  Divvy_Stations_2016_Q1Q2.csv
  Divvy_Stations_2016_Q3.csv
  Divvy_Stations_2016_Q4.csv
  Divvy_Trips_2016_04.csv
  Divvy_Trips_2016_05.csv
  Divvy_Trips_2016_06.csv
  Divvy_Trips_2016_Q1.csv
  Divvy_Trips_2016_Q3.csv
  Divvy_Trips_2016_Q4.csv
  ```

+ R packages that need to be installed: 
    - read.table from CRAN

<br>

## Session information

```{r session-info}
```